stages:
  - build
  - test

variables:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: yii2basic
  MYSQL_USER: yii2
  MYSQL_PASSWORD: yii2_password

services:
  - name: mariadb:10.4
    alias: db

build:
  stage: build
  script:
    - docker build -t yii2-app-basic .
  artifacts:
    paths:
      - vendor/
  only:
    - develop

test:
  stage: test
  script:
    - docker run -d -p 8080:80 yii2-app-basic
    - docker exec -it yii2-app-basic php vendor/bin/codecept run
  dependencies:
    - build
  only:
    - develop
